Add extra logic for leaving a comment

diff --git a/.github/workflows/sample-go-cicd-for-zero-test.yaml b/.github/workflows/sample-go-cicd-for-zero-test.yaml
--- a/.github/workflows/sample-go-cicd-for-zero-test.yaml
+++ b/.github/workflows/sample-go-cicd-for-zero-test.yaml
@@ -22,6 +22,8 @@ on:
 env:
   GO_VERSION: 1.20.5
   GO_WORKING_DIR: ./example/zero-test/
+  COVERAGE_THRESHOLD: "0"
+  CACHE_NAME: zero-test
 
 jobs:
   build:
@@ -48,7 +50,9 @@ jobs:
             ~/.cache/coverage.txt
             ~/.cache/go-build
             ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ env.GO_WORKING_DIR }}
+          key: go-${{ env.CACHE_NAME }}-${{ hashFiles('**') }}
+          restore-keys: |
+            go-${{ env.CACHE_NAME }}-
 
       # Go build and test -- note how this saves the coverage into a /tmp/ dir,
       # so that it could be compared to the cached coverage data.
@@ -66,7 +70,7 @@ jobs:
       # - name: Setup tmate session
       #   uses: mxschmitt/action-tmate@v3
 
-      - name: Check test coverage
+      - name: Get test coverage
         run: |
           ## Step 1. Check previous coverage
           if [[ -f ~/.cache/coverage.txt ]]; then
@@ -83,16 +87,31 @@ jobs:
           go tool cover -func=/tmp/coverage.out > /tmp/coverage.txt
           newCoverage=$(cat /tmp/coverage.txt | grep total | grep -Eo '[0-9]+\.[0-9]+')
           echo "New test coverage:      ${newCoverage}%"
+
+          ## Step 3. Set environment variables
+          echo "PREV_COVERAGE=$prevCoverage" >> $GITHUB_ENV
+          echo "NEW_COVERAGE=$newCoverage" >> $GITHUB_ENV
+
+      - name: Check coverage status
+        run: |
+          echo "Coverage Threshold:     ${{ env.COVERAGE_THRESHOLD }}%"
+          echo "Previous test coverage: ${{ env.PREV_COVERAGE || 'Unknown' }}%"
+          echo "New test coverage:      ${{ env.NEW_COVERAGE }}%"
           echo
 
-          ## Step 3. Check previous coverage <= new coverage
-          isNewWorse=$(bc <<< $prevCoverage > $newCoverage)
-          if (( $isNewWorse )); then
-          echo "ERROR: The new coverage is worse than the previous coverage, exiting as a failed check"
+          isBelowThreshold=$(bc <<< "${{ env.COVERAGE_THRESHOLD }} > ${{ env.NEW_COVERAGE }}")
+          if (( $isBelowThreshold )); then
+          echo "ERROR: The test coverage is below the threshold, exiting as failed."
           exit 1
-          else
-          echo "The new coverage is greater or equal to the previous coverage."
           fi
+
+          isNewWorse=$(bc <<< "${{ env.PREV_COVERAGE || '0' }} > ${{ env.NEW_COVERAGE }}")
+          if (( $isNewWorse )); then
+          echo "ERROR: The new coverage is worse than the previous coverage, exiting as failed."
+          exit 1
+          fi
+
+          echo "The new coverage is greater or equal to the previous coverage, and passes the threshold."
 
       # If triggered from non-PR setup, copy the new coverage as the new cached data.
       - name: Copy coverage information for cache
